# Site settings
title: On the Road to Sebbe's Blog
description: "Companion blog to the lynda.com course, Jekyll for Web Designers. This site is designed to present Jekyll to web designers in a clear, concise way, and provide a resource and reference for those that are new to Jekyll."
baseurl: "/sebbe02" 
url: "http://virsto.github.io/sebbe02" 
tagline: A basic guide to Jekyll

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
# The following is required for jekyll vers. 3+
gems: [jekyll-paginate]	
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
